-- ============================================================================
-- 0002_seed_bake_brothers — GENERADO por scripts/seed-from-mock.mjs.
-- No editar a mano: regenerar con
--   node scripts/seed-from-mock.mjs > migrations/0002_seed_bake_brothers.sql
-- ============================================================================

insert into tenants (slug, nombre, codigo_prefijo, telefono_whatsapp, direccion_tienda)
values ('bake-brothers', 'Bake Brothers', 'BB', '51987654321', 'Av. Los Pasteles 456, Miraflores')
on conflict (slug) do update set nombre = excluded.nombre, codigo_prefijo = excluded.codigo_prefijo;

insert into order_sequences (tenant_id, ultimo_numero)
values ((select id from tenants where slug = 'bake-brothers'), 2449)
on conflict (tenant_id) do nothing;

-- Categorías (6)
insert into categories (tenant_id, slug, nombre, tipo_producto, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'tortas', 'Tortas', 'Tortas', '🎂', '/img/torta-chocolate.jpg', '#F9E2D2', '#F0BE97', 'Para cumpleaños y celebraciones', 0)
on conflict (tenant_id, slug) do update set nombre = excluded.nombre, tipo_producto = excluded.tipo_producto, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, orden = excluded.orden;

insert into categories (tenant_id, slug, nombre, tipo_producto, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'postres', 'Postres', 'Postres', '🍰', '/img/tartas-fresas.jpg', '#FADDE4', '#F0AEBD', 'Cheesecakes, pies y más', 1)
on conflict (tenant_id, slug) do update set nombre = excluded.nombre, tipo_producto = excluded.tipo_producto, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, orden = excluded.orden;

insert into categories (tenant_id, slug, nombre, tipo_producto, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'dulces', 'Dulces', 'Dulces', '🍬', '/img/vitrina-dulces.jpg', '#FDEBD2', '#F6C88B', 'Alfajores, galletas y cupcakes', 2)
on conflict (tenant_id, slug) do update set nombre = excluded.nombre, tipo_producto = excluded.tipo_producto, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, orden = excluded.orden;

insert into categories (tenant_id, slug, nombre, tipo_producto, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'salados', 'Salados', 'Salados', '🥟', '/img/croissants.jpg', '#F5E9D4', '#E3C48F', 'Empanadas y quiches caseros', 3)
on conflict (tenant_id, slug) do update set nombre = excluded.nombre, tipo_producto = excluded.tipo_producto, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, orden = excluded.orden;

insert into categories (tenant_id, slug, nombre, tipo_producto, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'bocaditos', 'Bocaditos', 'Bocaditos', '🥪', '/img/bocaditos-vitrina.jpg', '#EFF0E2', '#CBD1A4', 'Para compartir en toda reunión', 4)
on conflict (tenant_id, slug) do update set nombre = excluded.nombre, tipo_producto = excluded.tipo_producto, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, orden = excluded.orden;

insert into categories (tenant_id, slug, nombre, tipo_producto, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'catering', 'Catering', 'Catering', '🎉', '/img/vitrina-pasteleria.jpg', '#FBE5D5', '#F2BA8C', 'Mesas dulces y eventos', 5)
on conflict (tenant_id, slug) do update set nombre = excluded.nombre, tipo_producto = excluded.tipo_producto, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, orden = excluded.orden;

-- Productos (26)
insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'torta-chocolate', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Tortas' limit 1), 'Torta de chocolate artesanal', 'dulces', 'Tortas', 76, 95, '🍫', '/img/torta-chocolate.jpg', '#F3DFC9', '#E4BE97', 'Bizcocho húmedo de cacao al 70%, relleno de fudge casero y cubierto con ganache brillante. Nuestra torta más pedida, hecha artesanalmente para compartir.', '12 – 15 porciones', 48, '48 horas de anticipación', null, 'Mantener refrigerada. Consumir dentro de 3 días.', true, true, true, 0)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'torta-red-velvet', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Tortas' limit 1), 'Torta red velvet', 'dulces', 'Tortas', 110, null, '❤️', null, '#F9DFDD', '#EFB6B0', 'Clásica torta de terciopelo rojo con frosting de queso crema batido. Suave, elegante y perfecta para celebraciones.', '12 – 15 porciones', 48, '48 horas de anticipación', null, 'Mantener refrigerada. Consumir dentro de 3 días.', true, true, true, 1)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'cheesecake-maracuya', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Postres' limit 1), 'Cheesecake de maracuyá', 'dulces', 'Postres', 65, null, '🥭', '/img/tartaletas-maracuya.jpg', '#FBEDCB', '#F2D48A', 'Base crocante de galleta, crema de queso sedosa y espejo de maracuyá natural. El equilibrio perfecto entre dulce y ácido.', '10 – 12 porciones', 24, '24 horas de anticipación', null, 'Mantener refrigerado. Consumir dentro de 4 días.', true, false, true, 2)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'cheesecake-frutos-rojos', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Postres' limit 1), 'Cheesecake de frutos rojos', 'dulces', 'Postres', 66, 78, '🍓', '/img/tartaletas-fresa.jpg', '#FADDE4', '#F0A8B8', 'Cheesecake horneado al estilo clásico, coronado con compota casera de fresas, arándanos y frambuesas.', '10 – 12 porciones', 24, '24 horas de anticipación', null, 'Mantener refrigerado. Consumir dentro de 4 días.', true, true, true, 3)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'brownies', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Postres' limit 1), 'Brownies artesanales (x6)', 'dulces', 'Postres', 28, null, '🟫', null, '#EBDCCB', '#CDAA82', 'Brownies densos y fudgy con trozos de chocolate bitter y nueces tostadas. Horneados el mismo día de tu entrega.', '6 unidades', 0, 'Mismo día (pedidos antes de las 12 pm)', '12:00', 'Ambiente fresco hasta 5 días.', true, false, true, 4)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'cupcakes-vainilla', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Dulces' limit 1), 'Cupcakes de vainilla (x6)', 'dulces', 'Dulces', 30, null, '🧁', null, '#FCEFDD', '#F5D3A0', 'Cupcakes esponjosos de vainilla de Madagascar con buttercream suave. Decoración clásica o personalizada.', '6 unidades', 24, '24 horas de anticipación', null, 'Ambiente fresco hasta 2 días, refrigerado hasta 4.', false, false, true, 5)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'cupcakes-chocolate', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Dulces' limit 1), 'Cupcakes de chocolate (x6)', 'dulces', 'Dulces', 32, null, '🧁', null, '#EFDFD3', '#D6B294', 'Cupcakes de cacao intenso con frosting de chocolate belga. Un clásico que nunca falla.', '6 unidades', 24, '24 horas de anticipación', null, 'Ambiente fresco hasta 2 días, refrigerado hasta 4.', false, false, true, 6)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'box-cupcakes', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Dulces' limit 1), 'Box de cupcakes (x12)', 'dulces', 'Dulces', 51, 68, '🎁', null, '#FDE8D2', '#F6C287', 'Caja surtida con 12 cupcakes: vainilla, chocolate, red velvet y zanahoria. Ideal para regalar o compartir en la oficina.', '12 unidades', 24, '24 horas de anticipación', null, 'Ambiente fresco hasta 2 días, refrigerado hasta 4.', true, false, true, 7)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'alfajores', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Dulces' limit 1), 'Alfajores artesanales (x12)', 'dulces', 'Dulces', 20, 25, '🍪', null, '#F6EBD9', '#E8CFA4', 'Alfajores de maicena que se deshacen en la boca, rellenos de manjar blanco casero y espolvoreados con azúcar impalpable.', '12 unidades', 0, 'Mismo día (pedidos antes de las 12 pm)', '12:00', 'Ambiente fresco hasta 7 días.', true, true, true, 8)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'galletas-artesanales', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Dulces' limit 1), 'Galletas artesanales (x10)', 'dulces', 'Dulces', 22, null, '🍪', null, '#F3E4CE', '#E3C395', 'Galletas con chispas de chocolate, avena y mantequilla de verdad. Crocantes por fuera, suaves por dentro.', '10 unidades', 0, 'Mismo día (pedidos antes de las 12 pm)', '12:00', 'Ambiente fresco hasta 7 días.', false, false, true, 9)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'tres-leches', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Tortas' limit 1), 'Torta tres leches', 'dulces', 'Tortas', 58, null, '🥛', '/img/tartas-fresas.jpg', '#F2EFE7', '#DED4BE', 'Bizcocho bañado en mezcla de tres leches, cubierto con merengue flameado y canela. Fresca, suave y preparada con cariño.', '10 – 12 porciones', 24, '24 horas de anticipación', null, 'Mantener refrigerada. Consumir dentro de 3 días.', true, false, true, 10)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'pie-limon', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Postres' limit 1), 'Pie de limón', 'dulces', 'Postres', 52, null, '🍋', null, '#FAF3CF', '#EBD87E', 'Masa quebrada horneada, crema de limón sutil y merengue italiano dorado. El postre favorito de las tardes.', '10 porciones', 24, '24 horas de anticipación', null, 'Mantener refrigerado. Consumir dentro de 3 días.', false, false, false, 11)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'empanadas-pollo', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Salados' limit 1), 'Empanadas de pollo (x6)', 'salados', 'Salados', 24, null, '🥟', null, '#F5E7D3', '#E5C08D', 'Empanadas horneadas con relleno jugoso de pollo deshilachado, aceituna y huevo. Masa hojaldrada hecha en casa.', '6 unidades', 0, 'Mismo día (pedidos antes de las 12 pm)', '12:00', 'Consumir el mismo día. Calentar 5 min al horno.', true, true, true, 12)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'empanadas-carne', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Salados' limit 1), 'Empanadas de carne (x6)', 'salados', 'Salados', 26, null, '🥟', null, '#F1DFCB', '#DCB183', 'Empanadas criollas de carne cortada a cuchillo, con el toque justo de ají panca y comino.', '6 unidades', 0, 'Mismo día (pedidos antes de las 12 pm)', '12:00', 'Consumir el mismo día. Calentar 5 min al horno.', false, false, true, 13)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'mini-triples', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Bocaditos' limit 1), 'Mini triples (x12)', 'salados', 'Bocaditos', 30, null, '🥪', null, '#EFF0E4', '#CBD1A9', 'Clásicos triples de palta, tomate y huevo en pan de molde artesanal, cortados en formato bocadito.', '12 unidades', 0, 'Mismo día (pedidos antes de las 12 pm)', '12:00', 'Refrigerar y consumir el mismo día.', true, false, true, 14)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'tequenos', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Bocaditos' limit 1), 'Tequeños de queso (x12)', 'salados', 'Bocaditos', 28, null, '🧀', null, '#FBF0D4', '#EDD089', 'Tequeños crocantes rellenos de queso fresco, acompañados de nuestra crema de palta casera.', '12 unidades + salsa', 0, 'Mismo día (pedidos antes de las 12 pm)', '12:00', 'Consumir el mismo día, recién fritos.', true, true, true, 15)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'quiches-personales', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Salados' limit 1), 'Quiches personales (x4)', 'salados', 'Salados', 36, null, '🥧', null, '#F4E9D6', '#E0C494', 'Quiches individuales de espinaca con queso y de jamón con champiñones. Masa quebrada mantecosa.', '4 unidades', 24, '24 horas de anticipación', null, 'Refrigerado hasta 2 días. Calentar al horno.', false, false, true, 16)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'bocaditos-mixtos', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Bocaditos' limit 1), 'Bocaditos mixtos (x24)', 'salados', 'Bocaditos', 55, null, '🍢', '/img/bocaditos-vitrina.jpg', '#F0E6DB', '#D4BDA2', 'Surtido de empanaditas, enrolladitos de hot dog, mini pizzas y tartaletas saladas. Perfecto para reuniones.', '24 unidades surtidas', 24, '24 horas de anticipación', null, 'Consumir el mismo día.', true, false, true, 17)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'sandwichitos-pollo', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Bocaditos' limit 1), 'Sandwichitos de pollo (x12)', 'salados', 'Bocaditos', 32, null, '🥖', null, '#F6EDDE', '#E4CBA0', 'Mini sánguches de pollo deshilachado con mayonesa casera en pan petit artesanal.', '12 unidades', 0, 'Mismo día (pedidos antes de las 12 pm)', '12:00', 'Refrigerar y consumir el mismo día.', false, false, true, 18)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'petipanes', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Bocaditos' limit 1), 'Petipanes surtidos (x12)', 'salados', 'Bocaditos', 34, null, '🥐', '/img/croissants.jpg', '#F3E6D2', '#DFC091', 'Petipanes rellenos de pollo, jamón inglés y queso con verduras frescas. Los infaltables de todo compartir.', '12 unidades', 0, 'Mismo día (pedidos antes de las 12 pm)', '12:00', 'Refrigerar y consumir el mismo día.', false, false, true, 19)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'box-cumpleanos', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Catering' limit 1), 'Box cumpleaños', 'catering', 'Catering', 120, null, '🎂', null, '#FDE7DA', '#F5B98E', 'Torta personal decorada, 6 cupcakes, 12 alfajores y globos. Todo listo para sorprender a esa persona especial.', 'Para 8 – 10 personas', 72, '72 horas de anticipación', null, 'Refrigerar hasta el momento de servir.', true, false, true, 20)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'mesa-dulce-basica', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Catering' limit 1), 'Mesa dulce básica', 'catering', 'Catering', 350, null, '🍮', '/img/mini-tartaletas-fruta.jpg', '#FBE9DD', '#F0C09A', 'Mesa dulce para 20 personas: torta central, cupcakes, brownies, alfajores y shots de postre. Incluye montaje básico.', 'Para 20 personas', 120, '5 días de anticipación', null, 'Coordinamos entrega y montaje el día del evento.', false, false, true, 21)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'mesa-dulce-premium', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Catering' limit 1), 'Mesa dulce premium', 'catering', 'Catering', 690, null, '✨', '/img/vitrina-pasteleria.jpg', '#F7E3D4', '#EBB98C', 'Mesa dulce para 40 personas con torta temática, postres finos, macarons, decoración completa y personal de apoyo.', 'Para 40 personas', 168, '7 días de anticipación', null, 'Coordinamos entrega y montaje el día del evento.', false, false, true, 22)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'box-corporativo', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Catering' limit 1), 'Box corporativo', 'catering', 'Catering', 180, null, '💼', '/img/vitrina-dulces.jpg', '#EEE9E2', '#CFC2AE', 'Box para reuniones de trabajo: bocaditos salados, mini postres y café de pasar para 10 personas. Presentación impecable.', 'Para 10 personas', 48, '48 horas de anticipación', null, 'Consumir el mismo día.', true, false, true, 23)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'pack-bocaditos-50', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Catering' limit 1), 'Pack bocaditos 50 unidades', 'catering', 'Catering', 95, null, '🥨', null, '#F4E8D8', '#E2C69B', '50 bocaditos surtidos entre dulces y salados, listos para servir. Elige la proporción que prefieras.', '50 unidades', 48, '48 horas de anticipación', null, 'Consumir el mismo día.', false, true, true, 24)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

insert into products (tenant_id, slug, category_id, nombre, categoria_negocio, tipo, precio_base, precio_anterior, emoji, foto_url, gradiente_desde, gradiente_hasta, descripcion, porciones, anticipacion_horas, anticipacion_texto, corte_mismo_dia, conservacion, popular, mas_vendido, disponible, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'pack-bocaditos-100', (select id from categories where tenant_id = (select id from tenants where slug = 'bake-brothers') and tipo_producto = 'Catering' limit 1), 'Pack bocaditos 100 unidades', 'catering', 'Catering', 175, null, '🥨', null, '#F0E2CE', '#DBB988', '100 bocaditos surtidos entre dulces y salados para eventos grandes. Incluye bandejas de presentación.', '100 unidades', 72, '72 horas de anticipación', null, 'Consumir el mismo día.', false, false, true, 25)
on conflict (tenant_id, slug) do update set category_id = excluded.category_id, nombre = excluded.nombre, categoria_negocio = excluded.categoria_negocio, tipo = excluded.tipo, precio_base = excluded.precio_base, precio_anterior = excluded.precio_anterior, emoji = excluded.emoji, foto_url = excluded.foto_url, gradiente_desde = excluded.gradiente_desde, gradiente_hasta = excluded.gradiente_hasta, descripcion = excluded.descripcion, porciones = excluded.porciones, anticipacion_horas = excluded.anticipacion_horas, anticipacion_texto = excluded.anticipacion_texto, corte_mismo_dia = excluded.corte_mismo_dia, conservacion = excluded.conservacion, popular = excluded.popular, mas_vendido = excluded.mas_vendido, disponible = excluded.disponible, orden = excluded.orden, actualizado_en = now();

-- Tamaños (6 productos × 3)
insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'torta-chocolate'), 'Personal', 1)
on conflict (product_id, tamano) do update set factor = excluded.factor;
insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'torta-chocolate'), 'Mediano', 1.35)
on conflict (product_id, tamano) do update set factor = excluded.factor;
insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'torta-chocolate'), 'Grande', 1.7)
on conflict (product_id, tamano) do update set factor = excluded.factor;

insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'torta-red-velvet'), 'Personal', 1)
on conflict (product_id, tamano) do update set factor = excluded.factor;
insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'torta-red-velvet'), 'Mediano', 1.35)
on conflict (product_id, tamano) do update set factor = excluded.factor;
insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'torta-red-velvet'), 'Grande', 1.7)
on conflict (product_id, tamano) do update set factor = excluded.factor;

insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'cheesecake-maracuya'), 'Personal', 1)
on conflict (product_id, tamano) do update set factor = excluded.factor;
insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'cheesecake-maracuya'), 'Mediano', 1.35)
on conflict (product_id, tamano) do update set factor = excluded.factor;
insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'cheesecake-maracuya'), 'Grande', 1.7)
on conflict (product_id, tamano) do update set factor = excluded.factor;

insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'cheesecake-frutos-rojos'), 'Personal', 1)
on conflict (product_id, tamano) do update set factor = excluded.factor;
insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'cheesecake-frutos-rojos'), 'Mediano', 1.35)
on conflict (product_id, tamano) do update set factor = excluded.factor;
insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'cheesecake-frutos-rojos'), 'Grande', 1.7)
on conflict (product_id, tamano) do update set factor = excluded.factor;

insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'tres-leches'), 'Personal', 1)
on conflict (product_id, tamano) do update set factor = excluded.factor;
insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'tres-leches'), 'Mediano', 1.35)
on conflict (product_id, tamano) do update set factor = excluded.factor;
insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'tres-leches'), 'Grande', 1.7)
on conflict (product_id, tamano) do update set factor = excluded.factor;

insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'pie-limon'), 'Personal', 1)
on conflict (product_id, tamano) do update set factor = excluded.factor;
insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'pie-limon'), 'Mediano', 1.35)
on conflict (product_id, tamano) do update set factor = excluded.factor;
insert into product_sizes (tenant_id, product_id, tamano, factor)
values ((select id from tenants where slug = 'bake-brothers'), (select id from products where tenant_id = (select id from tenants where slug = 'bake-brothers') and slug = 'pie-limon'), 'Grande', 1.7)
on conflict (product_id, tamano) do update set factor = excluded.factor;

-- Extras (3)
insert into extras (tenant_id, slug, nombre, precio, activo)
values ((select id from tenants where slug = 'bake-brothers'), 'dedicatoria', 'Dedicatoria personalizada', 8, true)
on conflict (tenant_id, slug) do update set nombre = excluded.nombre, precio = excluded.precio;

insert into extras (tenant_id, slug, nombre, precio, activo)
values ((select id from tenants where slug = 'bake-brothers'), 'vela', 'Vela de celebración', 8, true)
on conflict (tenant_id, slug) do update set nombre = excluded.nombre, precio = excluded.precio;

insert into extras (tenant_id, slug, nombre, precio, activo)
values ((select id from tenants where slug = 'bake-brothers'), 'decoracion-especial', 'Decoración especial', 8, true)
on conflict (tenant_id, slug) do update set nombre = excluded.nombre, precio = excluded.precio;

-- Zonas de delivery (11)
insert into delivery_zones (tenant_id, nombre, activo, tarifa_delivery, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'Miraflores', true, null, 0)
on conflict (tenant_id, nombre) do update set activo = true, orden = excluded.orden;

insert into delivery_zones (tenant_id, nombre, activo, tarifa_delivery, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'San Isidro', true, null, 1)
on conflict (tenant_id, nombre) do update set activo = true, orden = excluded.orden;

insert into delivery_zones (tenant_id, nombre, activo, tarifa_delivery, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'Surco', true, null, 2)
on conflict (tenant_id, nombre) do update set activo = true, orden = excluded.orden;

insert into delivery_zones (tenant_id, nombre, activo, tarifa_delivery, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'San Borja', true, null, 3)
on conflict (tenant_id, nombre) do update set activo = true, orden = excluded.orden;

insert into delivery_zones (tenant_id, nombre, activo, tarifa_delivery, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'Barranco', true, null, 4)
on conflict (tenant_id, nombre) do update set activo = true, orden = excluded.orden;

insert into delivery_zones (tenant_id, nombre, activo, tarifa_delivery, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'La Molina', true, null, 5)
on conflict (tenant_id, nombre) do update set activo = true, orden = excluded.orden;

insert into delivery_zones (tenant_id, nombre, activo, tarifa_delivery, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'Jesús María', true, null, 6)
on conflict (tenant_id, nombre) do update set activo = true, orden = excluded.orden;

insert into delivery_zones (tenant_id, nombre, activo, tarifa_delivery, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'Magdalena', true, null, 7)
on conflict (tenant_id, nombre) do update set activo = true, orden = excluded.orden;

insert into delivery_zones (tenant_id, nombre, activo, tarifa_delivery, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'Pueblo Libre', true, null, 8)
on conflict (tenant_id, nombre) do update set activo = true, orden = excluded.orden;

insert into delivery_zones (tenant_id, nombre, activo, tarifa_delivery, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'Lince', true, null, 9)
on conflict (tenant_id, nombre) do update set activo = true, orden = excluded.orden;

insert into delivery_zones (tenant_id, nombre, activo, tarifa_delivery, orden)
values ((select id from tenants where slug = 'bake-brothers'), 'Surquillo', true, null, 10)
on conflict (tenant_id, nombre) do update set activo = true, orden = excluded.orden;

-- Cupones
insert into coupons (tenant_id, codigo, tipo, valor, activo)
values ((select id from tenants where slug = 'bake-brothers'), 'BAKE10', 'porcentaje', 10, true)
on conflict (tenant_id, codigo) do update set tipo = excluded.tipo, valor = excluded.valor, activo = excluded.activo;
